// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq8Xp8G4QTQl68EZ2TVSWm_9Y8VUZC-Xk',
    appId: '1:352189617145:android:8322444e310984e4d9e328',
    messagingSenderId: '352189617145',
    projectId: 'pontozz',
    storageBucket: 'pontozz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaeqdjqClp7zdunxL15SGpGjy7Jf2KZc',
    appId: '1:352189617145:ios:9844a79f8e858073d9e328',
    messagingSenderId: '352189617145',
    projectId: 'pontozz',
    storageBucket: 'pontozz.appspot.com',
    androidClientId: '352189617145-5ubkq6uod33auaon5gj1rthuppcb8kpd.apps.googleusercontent.com',
    iosClientId: '352189617145-sqoq2uj8qe5t1dibimkej94s3i94j259.apps.googleusercontent.com',
    iosBundleId: 'com.parkmobil.pontozz',
  );
}
